heat_template_version: 2014-10-16


description: >
  A template providing openstack resources related to loadbalancer.


parameters:

  external_network:
    type: string
    constraints:
    - custom_constraint: neutron.network

  fixed_network:
    type: string
    constraints:
    - custom_constraint: neutron.network

  fixed_subnet:
    type: string
    constraints:
    - custom_constraint: neutron.subnet

  lb_members:
    type: comma_delimited_list
    default: []

resources:

  lb:
    type: OS::Neutron::LoadBalancer
    properties:
      protocol_port: 8443
      pool_id: {get_resource: pool}
      members: {get_param: lb_members}

  pool:
    type: OS::Neutron::Pool
    properties:
      name: lb_pool
      description: Load balancer for OpenShift hosts.
      protocol: HTTPS
      subnet_id: {get_param: fixed_subnet}
      lb_method: ROUND_ROBIN
      monitors: [{get_resource: monitor}]
      vip:
        name: lb_vip
        description: broker virtual IP (VIP)
        protocol_port: 8443
        session_persistence:
          type: SOURCE_IP

  monitor:
    type: OS::Neutron::HealthMonitor
    properties:
      type: TCP
      delay: 15
      max_retries: 5
      timeout: 10

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: {get_param: external_network}
      port_id: {get_attr: [pool, vip, port_id]}

outputs:
  floating_ip:
    value: {get_attr: [floating_ip, floating_ip_address]}

  #console_url:
  #  value:
  #    str_replace:
  #      params:
  #        HOSTNAME: {get_param: hostname}
  #        DOMAINNAME: {get_param: domain_name}
  #      template: "https://HOSTNAME.DOMAINNAME:8443/console/"

  #api_url:
  #  value:
  #    str_replace:
  #      params:
  #        HOSTNAME: {get_param: hostname}
  #        DOMAINNAME: {get_param: domain_name}
  #      template: "https://HOSTNAME.DOMAINNAME:8443/"
